<a href="https://colab.research.google.com/github/PremGorecki/DataScience/blob/main/01_wprowadzenie/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

np.__version__

dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
print(x)

print(type(x))

x.ndim
x.shape
x.size
x.dtype 

[1 3]
<class 'numpy.ndarray'>


dtype('int64')

In [ ]:
y = np.array([1.3, 2.4, 3.5])

y.ndim

y.shape

y.size

y.dtype 

dtype('float64')

In [ ]:
x = np.array([[1, 2], [-3, 1]])

print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(2, 2)
4
int64


In [ ]:
x = np.array([[1, 2, 4], [4, 2, 1]])

print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(2, 3)
6
int64


TYPY DANYCH

In [ ]:
A = np.array([1, 2, 3], dtype='float')
print(A.dtype)



In [ ]:
A = np.array([1, 2, 3], dtype=np.int8)
print(A.dtype)

In [ ]:

A = np.array([1, 2, 3], dtype=np.uint8)
print(A.dtype)

TWORZENIE TABLIC


In [ ]:
A = np.zeros(shape=(4, 10), dtype = 'int')

print(A)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
B = np.ones(shape = (5, 5), dtype = 'int')

print(B)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
C = np.full(shape =(3, 3), fill_value=4, dtype='int')
print(C)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [ ]:
D = np.arange(10)
print(D)

In [ ]:
D = np.arange(start = 10, stop = 100, step = 10)
print(D)

[10 20 30 40 50 60 70 80 90]


In [ ]:
E = np.linspace(start = 0, stop = 1, num = 11)
print(E)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
F = np.arange(15)
F.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
F = np.arange(15)
F.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

OPERACJE NA TABLICACH 

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B

np.add(A, B)

array([6, 0, 7, 4])

In [ ]:

A * B

np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
A - B
np.subtract(A, B)


array([0, 2, 1, 0])

In [ ]:
A / B
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
print(A +3)

[6 4 7 5]


In [ ]:
print(2 * A)

[6 2 8 4]


In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

print(X)
print(Y)
print('-----------')
print(X * Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]
-----------
[[6 0]
 [2 0]]


GENEROWANIE LICZB PSEUDOLOSOWYCH

In [ ]:
np.random.seed(0)
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand(5, 2)

array([[0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772]])

In [ ]:
np.random.randint(low=10, high=101, size=(5,4))

array([[45, 77, 92, 56],
       [30, 91, 60, 37],
       [24, 51, 68, 75],
       [46, 20, 96, 53],
       [21, 12, 61, 90]])

In [ ]:
np.random.choice([5, 2, 3, 1, 4])

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [ ]:
data = np.arange(10)
np.random.shuffle(data)
print(data)

[4 5 0 1 7 9 6 3 2 8]


PODSTAWOWE FUNKCJE W BIBLIOTECE NUMPY

In [6]:
np.exp(1)
np.sqrt(9)

np.all([1, 2, 0])

False

In [7]:
np.any([1, 3, 0])

True

In [9]:
A = np.random.rand(5)
A

array([ 0.59921493, -0.36733089,  0.28633452,  2.10950284, -2.00604389])

In [10]:
np.argmax(A)

3

In [11]:
np.argsort(A)

array([4, 1, 2, 0, 3])

In [12]:
np.argmin(A)

4

In [13]:
np.max(A)

2.1095028375915024

In [14]:
np.min(A)

-2.0060438907664837

In [15]:
np.mean(A)

0.12433549973658539

In [16]:
np.median(A)

0.2863345175080902

In [17]:
np.std(A)

1.339619028019851

INDEKSOWANIE I WYCINANIE TABLIC

In [18]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
A[2]

2

In [20]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [21]:
A[:2]

array([0, 1])

In [22]:
A[[0, 2]]

array([0, 2])

In [23]:
A[-1]

19

In [24]:
A[10 : 15]

array([10, 11, 12, 13, 14])

In [26]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
A[1]

array([5, 6, 7, 8, 9])

In [29]:
A[:,0]

array([ 0,  5, 10, 15])

In [30]:
A[:,-1]

array([ 4,  9, 14, 19])

In [31]:
A[1, 1]

6

In [32]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

 ITERACJA PO TABLICACH

In [33]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [34]:
for row in A:
  print(row[0])

0
5
10
15


In [35]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [37]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [48]:
B = np.arange(start=-10, stop=10, step=0.5)

In [49]:
B = B.reshape(10, -1)
B

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [51]:
B > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
B [B > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [56]:
np.bitwise_and(B > -5 , B < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [58]:
np.bitwise_or(B < -5, B >5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])