<a href="https://colab.research.google.com/github/PremGorecki/DataScience/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



In [5]:
v1 = np.array([-1, 4])

In [4]:
v1

array([0, 4])

In [6]:
np.linalg.norm(v1)

4.123105625617661

In [8]:
v2 = np.array([-10, 10, 13])

np.linalg.norm(v2)

19.209372712298546

In [9]:

p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [10]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p - q)

5.0990195135927845

In [12]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[-1], [1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[-1]
 [ 1]]


In [13]:
Z = np.dot(X, Y)
print(Z)

[[-2]
 [ 6]]


In [14]:
A = np.array([[2, 4], [-1,3]])
print(A)

[[ 2  4]
 [-1  3]]


In [15]:
print(np.linalg.det(A))

9.999999999999998


In [17]:
print(np.trace(A))

5


In [19]:
B = np.eye(5, dtype = int)
print(B)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [20]:
A

array([[ 2,  4],
       [-1,  3]])

In [22]:
B = np.linalg.inv(A)

In [24]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)


array([[1., 0.],
       [0., 1.]])

In [25]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [27]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [28]:

A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [29]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [31]:
A_inv = np.linalg.inv(A)

In [33]:
X = np.dot(A_inv, B)
print(X)

[[1.]
 [2.]]


In [34]:
price = np.array([  [12.4, 12.8, 11.9, 12.6, 1000],
                    [12.5, 13.0, 11.7, 12.2, 2000],
                    [12.2, 13.4, 12.0, 13.2, 1500]
                  ])

#rint(price)

print(price.sum(axis=0))


print(price.sum(axis=1))

print(np.sum(price))

print(np.min(price, axis=0))

print(np.max(price, axis=0))

print(np.median(price))

print(np.mean(price))


print(np.std(price))

print(np.var(price))

[  37.1   39.2   35.6   38.  4500. ]
[1049.7 2049.4 1550.8]
4649.9
[  12.2   12.8   11.7   12.2 1000. ]
[  12.5   13.4   12.    13.2 2000. ]
12.6
309.9933333333333
622.3845322271076
387362.5059555555
