<a href="https://colab.research.google.com/github/PremGorecki/DataScience/blob/main/06_uczenie_maszynowe/01_sklearn_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Uczenie nadzorowane - klasyfikacja

import sklearn
sklearn.__version__

'1.0.2'

In [ ]:
import numpy as np
from sklearn import datasets  #sajkit learn

np.random.seed(10)  #ziarno losowe - aby wszędzie tam gdzie losujemy były takie same dane
raw_data = datasets.load_iris() # gatunki kosaćca
raw_data  # mamy dane w SŁOWNIKU  raw data

In [3]:
# wyświetlamy klucze 
raw_data.keys()

# data - nasze dane wejściowe
# target - nasze dane docelowe
# target_names - nazwa naszej zmiennej docelowej
# DESC - krotki opis
# feature_names - nazwy naszych cech
# filename - lokalizacja gdzie się plik znajduje


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
# opis aby zobaczyć o co chodzi

print(raw_data.DESCR)

In [5]:
# przygotowujemy nasze dane do modelu
# wyciągamy dane i odpowiedzi
data = raw_data.data
target = raw_data.target

In [6]:
# sprawdzamy czy rozmiary się zgadzają
# obowiązkowy krok
print(data.shape)
print(target.shape)

# nie robimy wizualizalizacji ale to też obowiązkowy krok

(150, 4)
(150,)


In [7]:
# standardowe dzielimy dane na treningowe i testowe() Czas jeszcze zbiór walidaycyjny

# importujemy funkcja ktora te dane dzieli
from sklearn.model_selection import train_test_split
# zwarca 4 obiekty numpy array
# na dane testowe w zależności od problemu przeznaczamy 20-30%. Jeżeli ich jest dużo to mniej %
# u nas 30 % na dane testowe
data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3)

In [8]:
print(data_train.shape)
print(target_train.shape)

(105, 4)
(105,)


In [9]:
print(data_test.shape)
print(target_test.shape)

(45, 4)
(45,)


In [ ]:
# importujemy klasę która przechowuje nasz model
# regresja logistyczna - jest to model klasyfikacji
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()  # tworzymy instancję tej klasy
model.fit(data_train, target_train) # przetrenowujemy model na naszych danych treningowych
# poniżej dostaniemy info o dodatkowych parametrach które zostały przyjęte 

In [11]:
# robimy predykcję na danych testowych
# przekazujemy tylko cechy a nie target
target_pred = model.predict(data_test)
print(target_pred)

[1 2 0 1 0 1 1 1 0 1 1 2 1 0 0 2 1 0 0 0 2 2 2 0 1 0 1 1 1 2 1 1 2 2 2 0 2
 2 2 2 0 0 1 0 1]


In [12]:
# do oceny modelu mamy np. dwa narzędzia macierz konfuzji i raport klasyfikacji
# MACIERZ KONFUZJI
from sklearn.metrics import confusion_matrix

confusion_matrix(target_test, target_pred)

# klasę pierwsza array([[15,  0,  0], przewidział w 100% poprawnie
# to co nas interesuje to maksymalizacja wartości na przekątnej macierzy

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [13]:
# jeszcze jedna funkcja która pozwoli ocenić model - RAPORT KLASYFIKACJI

from sklearn.metrics import classification_report
print(classification_report(target_test, target_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [14]:
model.coef_

array([[-0.3533224 ,  0.91306745, -2.23703308, -0.97687265],
       [ 0.56194662, -0.4405913 , -0.21698792, -0.64601958],
       [-0.20862422, -0.47247615,  2.454021  ,  1.62289223]])

In [15]:
model.intercept_

array([  8.30708662,   1.77287532, -10.07996194])