<a href="https://colab.research.google.com/github/PremGorecki/DataScience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.__version__

dir(np)

In [ ]:
help(np.array)

In [12]:
x = np.array([1, 3])
print(x)

print(type(x))

x.ndim
x.shape
x.size
x.dtype 

[1 3]
<class 'numpy.ndarray'>


dtype('int64')

In [14]:
y = np.array([1.3, 2.4, 3.5])

y.ndim

y.shape

y.size

y.dtype 

dtype('float64')

In [17]:
x = np.array([[1, 2], [-3, 1]])

print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(2, 2)
4
int64


In [18]:
x = np.array([[1, 2, 4], [4, 2, 1]])

print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(2, 3)
6
int64


TYPY DANYCH

In [ ]:
A = np.array([1, 2, 3], dtype='float')
print(A.dtype)



In [ ]:
A = np.array([1, 2, 3], dtype=np.int8)
print(A.dtype)

In [ ]:

A = np.array([1, 2, 3], dtype=np.uint8)
print(A.dtype)

TWORZENIE TABLIC


In [27]:
A = np.zeros(shape=(4, 10), dtype = 'int')

print(A)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [28]:
B = np.ones(shape = (5, 5), dtype = 'int')

print(B)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [29]:
C = np.full(shape =(3, 3), fill_value=4, dtype='int')
print(C)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [ ]:
D = np.arange(10)
print(D)

In [31]:
D = np.arange(start = 10, stop = 100, step = 10)
print(D)

[10 20 30 40 50 60 70 80 90]


In [33]:
E = np.linspace(start = 0, stop = 1, num = 11)
print(E)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [34]:
F = np.arange(15)
F.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
F = np.arange(15)
F.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

OPERACJE NA TABLICACH 

In [36]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [43]:
A + B

np.add(A, B)

array([6, 0, 7, 4])

In [38]:

A * B

np.multiply(A, B)

array([ 9, -1, 12,  4])

In [39]:
A - B
np.subtract(A, B)


array([0, 2, 1, 0])

In [44]:
A / B
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [41]:
print(A +3)

[6 4 7 5]


In [42]:
print(2 * A)

[6 2 8 4]


In [45]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

print(X)
print(Y)
print('-----------')
print(X * Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]
-----------
[[6 0]
 [2 0]]
