<a href="https://colab.research.google.com/github/PremGorecki/DataScience/blob/main/10_testy/01_testowy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


df = pd.DataFrame(data={'col1': [1, 2], 'col2': [5, 4]}, dtype=np.float64)
df.columns = ['One', 'Two']
df = df.sort_values('Two', ascending=True)

data2 = np.array(['Jan', 'Przemek'])
df2 = pd.DataFrame(data=data2, columns=['Name'])

# axis = 0 to pod spodem dodaje
# axis = 1 to jako kolumna
df = pd.concat([df, df2], axis=0)
print(df)



In [18]:
#RESHAPE

X = np.array([[1, 2, 3], [3, 4 ,5]])
print(X, X.shape)
print()

X = X.reshape(1, -1)
print(X, X.shape)


[[1 2 3]
 [3 4 5]] (2, 3)

[[1 2 3 3 4 5]] (1, 6)
