<a href="https://colab.research.google.com/github/PremGorecki/DataScience/blob/main/07_uczenie_glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.8.2'

Wprowadzenie - pierwszy model

In [ ]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy Dense. Aby dodać warstwę do modelu należy użyć metody .add()

In [ ]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))  #input shape - mówi ile cech tu wchodzi


Wyświetlenie podsumowania modelu: metoda .summary()

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


FUNKCJE AKTYWCJI

In [ ]:
#LINOWA

from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
#liczymy na danych funkcję linear czyli te same dane dotajemy bo ona x->x
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [ ]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [ ]:
#SIGMOID
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [ ]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [ ]:
# RELU

from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [ ]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [ ]:
# TAN HIPERBOLICZNY

from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [ ]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [ ]:
# Robimy nowy model

model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:

rodzaj optymalizatora (Keras - Optymalizatory)
funkcję straty (Keras - Funkcje Straty)
metryki, które będziemy obserwować podczas trenowania sieci (Keras - Metryki)

In [ ]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

Przykład - klasyfikacja binarna

In [ ]:
data = np.random.randn(10000, 150)  # 10 tys próbek i 150 zmiennych niezależnych
labels = np.random.randint(2, size=(10000, 1)) # labelki do tych 10 tys próbek

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [ ]:
data[:3]

In [ ]:
labels[:10]

In [ ]:
# Teraz budujemy model klasyfikacji binarnej

model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid')) # tu mamy klsyfikację binarną to musi być 1 naurow
# i funkcja sigmoid któa zwarac pradwopobioneństow

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

In [ ]:
# batch size na 64 aktualizujemy wagi co 64 próbki 
# to model się szybciej trenuje

model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

In [ ]:
# teraz walidation split na 0.2
# tu są ważne te wartości na zbiorze walidacyjnym 
# val_loss: 0.7247 - val_accuracy: 0.5115

# UWAGA loss: 0.4620 - accuracy: 0.7906 - te się poprawiają
# ale ważne jest jak nasz model dziala na danych któreych nie widział
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

In [ ]:
# teraz verbose=0
# nie ma tych logów z trenowania - tylko sam wynik
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [ ]:
metrics = history.history
metrics.keys()
metrics.values()

In [ ]:
# verbose na 1
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

DANE TESTOWE DO DOKONANIA PREDYKCJI

In [ ]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [ ]:
model.predict(test_data)

array([[0.0206143 ],
       [0.92120785],
       [0.8390899 ],
       [0.9293053 ],
       [0.51595736]], dtype=float32)

In [ ]:
# model.predict_proba(test_data)
# model.predict_classes(test_data)

predict_x=model.predict(test_data)
classes_x = np.argmax(predict_x,axis=1)

y_pred = classes_x

y_pred


array([0, 0, 0, 0, 0])

Przykład - klasyfikacja wieloklasowa

In [34]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [35]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [36]:
labels[:10]

array([[0],
       [0],
       [4],
       [2],
       [6],
       [8],
       [5],
       [1],
       [7],
       [9]])

In [37]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [38]:
labels[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [39]:
# Budujemy model

model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax')) # softmax zwróci nam pradopo

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3144 - accuracy: 0.0966 - val_loss: 2.3056 - val_accuracy: 0.0955
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 2.3032 - accuracy: 0.1029 - val_loss: 2.3068 - val_accuracy: 0.0945
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 2.3019 - accuracy: 0.1077 - val_loss: 2.3074 - val_accuracy: 0.0950
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2997 - accuracy: 0.1112 - val_loss: 2.3188 - val_accuracy: 0.1030
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2984 - accuracy: 0.1141 - val_loss: 2.3113 - val_accuracy: 0.0975
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2953 - accuracy: 0.1215 - val_loss: 2.3132 - val_accuracy: 0.0980
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2916 - accuracy: 0.1259 - val_loss: 2.3171 - val_accuracy: 0.1015
Epoch 

In [40]:
# teraz losujemy sobie dane testowe

test_data = np.random.random((10, 150))

model.predict(test_data)

array([[0.07190087, 0.09915317, 0.10246824, 0.10062326, 0.13516033,
        0.09292273, 0.11867303, 0.10311092, 0.11374165, 0.06224588],
       [0.10272413, 0.04495262, 0.05711671, 0.04804498, 0.2296077 ,
        0.07890372, 0.15555117, 0.09969946, 0.09060435, 0.09279523],
       [0.10824066, 0.04353978, 0.04186396, 0.04808237, 0.19696365,
        0.09554885, 0.18137105, 0.085512  , 0.05952104, 0.1393567 ],
       [0.10446708, 0.10598982, 0.09723153, 0.0805323 , 0.11320948,
        0.1039959 , 0.05770229, 0.13723408, 0.07669604, 0.1229415 ],
       [0.05732869, 0.11985654, 0.0698661 , 0.11115525, 0.20787865,
        0.06918716, 0.11391648, 0.12818235, 0.07026973, 0.05235911],
       [0.14541349, 0.0522658 , 0.04892263, 0.07675213, 0.10301872,
        0.05307207, 0.14021014, 0.12096076, 0.16108458, 0.09829969],
       [0.20680885, 0.06558283, 0.02063615, 0.07118344, 0.06836868,
        0.06844299, 0.11665852, 0.0790641 , 0.03086005, 0.27239433],
       [0.07472052, 0.04672314, 0.1053669

In [41]:
# model.predict_classes(test_data)

predict_x=model.predict(test_data)
classes_x = np.argmax(predict_x,axis=1)

y_pred = classes_x

y_pred

array([4, 4, 4, 7, 4, 8, 9, 4, 6, 7])

Przykład - regresja

In [42]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [43]:
labels[:10]

array([12.46368297, 17.55159208,  2.96767019, 33.3812404 , 34.26833545,
        9.218078  , 14.38686423, 41.1342143 , 43.89282353, 40.06396386])

In [47]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1)) # tu 1 neuron bez funkcji aktywacji bo przewidujemy jedną wartość


model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 1ms/step - loss: 262.7854 - val_loss: 209.3380
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 211.2435 - val_loss: 207.1698
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 210.6796 - val_loss: 207.0665
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 210.5399 - val_loss: 207.1465
Epoch 5/30
250/250 [==============================] - 0s 2ms/step - loss: 210.0154 - val_loss: 207.1923
Epoch 6/30
250/250 [==============================] - 0s 2ms/step - loss: 209.4078 - val_loss: 207.3869
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 209.4914 - val_loss: 209.7509
Epoch 8/30
250/250 [==============================] - 0s 1ms/step - loss: 209.1422 - val_loss: 207.8000
Epoch 9/30
250/250 [==============================] - 0s 1ms/step - loss: 208.9471 - val_loss: 207.7720
Epoch 10/30
250/250 [==============================] - 0s 1ms/st

In [46]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae', # tu inna funkcja straty
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 14.0234 - mse: 285.9216 - val_loss: 12.4425 - val_mse: 206.5472
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 12.5298 - mse: 211.5005 - val_loss: 12.4712 - val_mse: 208.1131
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 12.5135 - mse: 211.1186 - val_loss: 12.4449 - val_mse: 206.6658
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 12.5082 - mse: 210.8046 - val_loss: 12.4504 - val_mse: 206.9344
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 12.4998 - mse: 210.2609 - val_loss: 12.4624 - val_mse: 207.5872
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 12.4909 - mse: 210.2682 - val_loss: 12.4603 - val_mse: 207.4403
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 12.4786 - mse: 210.0963 - val_loss: 12.4713 - val_mse: 207.9911
Epoch 8/30
250/250 [==============

In [48]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[27.18553 ],
       [24.041998],
       [25.249903],
       [26.25954 ],
       [22.522097],
       [22.177397],
       [23.695505],
       [28.009472],
       [19.112123],
       [24.344072]], dtype=float32)